name: Stale Issues / PRs

on:
    schedule:
        - cron: '00 10 * * *'

jobs:
    statle:
        name: Check for Stale Issues / PRs
        runs-on: ubuntu-latest
        steps:
            - name: Stale
              uses: actions/stale@v9
              with:
                close-issue-message: >
                    This issue was closed because it has been stale for 10 days with no activity.
                close-pr-message: >
                    This PR was closed because it has been stale for 10 days with no activity.
                days-before-stale: 120
                days-before-close: 10
                days-before-pr-close: -1
                exempt-all-assignees: true
                exempt-all-pr-milestones: true
                exempt-issue-labels: 'planned,added,fixed,meta: no-stale'
                exempt-pr-labels: 'dependencies,i18n,meta: no-stale'
                stale-issue-label: 'meta: stale'
                stale-issue-message: >
                    This issue was marked as stale because there has been no activity in the past 120 days.
                    To remove this label, set the label `meta: no-stale`, or interact with this issue.

